source 'https://rubygems.org'
gem 'rails', '~> 7.0', '>= 7.0.8.1'
gem 'mysql2'
gem 'sass-rails', '>= 5.0.8'
gem 'uglifier'
gem 'coffee-rails', '>= 5.0.0'
gem 'jquery-rails', '>= 4.3.2'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari', '>= 1.2.0'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope', '>= 2.0.2'
gem 'florrick'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies', '>= 1.0.3'
gem 'log_logins'

group :development, :test do
  gem 'annotate', '~> 2.6.5'
end
