source 'https://rubygems.org'
gem 'rails', '~> 6.1', '>= 6.1.7.3'
gem 'mysql2'
gem 'sass-rails', '>= 6.0.0'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails', '>= 4.4.0'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari', '>= 1.2.1'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma', '>= 4.3.12'
gem 'moonrope', '>= 2.0.2'
gem 'florrick'
gem 'delayed_job_active_record', '>= 4.1.5'
gem 'foreman'
gem 'redcarpet', '>= 3.5.1'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins'

group :development, :test do
  gem 'annotate', '~> 2.7.2'
end
